[functions]
  external_node_modules = ["express"]
  included_files = ["./netlify/functions/client/**", "./netlify/functions/server/**", "./netlify/functions/functions/**"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/server-prod/:splat"
